import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { SessionProvider } from "next-auth/react";
import LayoutHeader from "@/components/LayoutHeader";
import { cn } from "@/utils/cn";
import { GridDotBackground } from "@/components/GridDotBackground";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className,"flex flex-col min-h-[100dvh] relative")}>
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <GridDotBackground />
            <LayoutHeader/>
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
